---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes
      
- name: "copy distribution zip"
  become: true
  copy:
    src: backend_artifact.tar.gz
    dest: backend_artifact.tar.gz

- name: "Unpack dist files"
  become: true
  shell: |
    tar -xzf backend_artifact.tar.gz
    rm backend_artifact.tar.gz

- name: "set variables"
  become: true
  environment:
  
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./dist/modules/domain/*/*/*.entity.js
    TYPEORM_HOST: postgres.cslksjoz5psg.us-west-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: test1234
    TYPEORM_DATABASE: postgres
  shell: |
    nohup node /home/ubuntu/dist/main.js &
    
- name: "check backend services stats"
  become: true
  shell: |
    netstat -a |grep 3030
